![](../../img/logot.png)

# INTRODUCTION OF NUMPY

# INSTALLATION OF NUMPY

conda install numpy
conda install -c anaconda numpy

In [12]:
import numpy as np

In [4]:
an_array = numpy.array([3, 33,333])
print(an_array)

[  3  33 333]


# ND-ARRAY: BASIC

1 - Dimensional Array

In [7]:
my_array = [1,2,3] 
my_array

[1, 2, 3]

2 - Dimensional Array

In [8]:
my_mat = [[1,2,3],[4,5,6]]
my_mat

[[1, 2, 3], [4, 5, 6]]

In [9]:
an_array = np.array([3, 33,333])
print(an_array)

[  3  33 333]


In [10]:
print(type(an_array))  #CHECKING THE TYPE

<class 'numpy.ndarray'>


In [11]:
print(an_array.shape) #CHECKING THE SHAPE

(3,)


In [12]:
print(an_array.dtype) #CHECKING THE DATA TYPE

int64


In [13]:
print(an_array.size) #CHECKING THE SIZE

3


In [14]:
print(an_array.ndim) #CHECKING THE DIMENSION

1


In [15]:
print(an_array.itemsize)

8


In [18]:
arr= np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
print(arr.ndim)

1


In [21]:
arr= np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [22]:
print(arr.ndim)

2


In [23]:
arr.shape

(3, 5)

In [24]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
np.ones((2,3,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [27]:
np.empty((3,4))

array([[4.44659081e-323, 6.94688321e-310, 4.65181700e-310,
                    nan],
       [0.00000000e+000,             nan, 6.94690417e-310,
        6.94677762e-310],
       [3.55727265e-322, 3.45845952e-323, 6.94688321e-310,
        4.65181700e-310]])

In [31]:
np.arange(8,30,4)

array([ 8, 12, 16, 20, 24, 28])

In [32]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [34]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [35]:
np.random.rand(5)

array([0.75409599, 0.74410288, 0.7131212 , 0.57401636, 0.02569991])

In [37]:
np.random.rand(5,5)

array([[0.35353371, 0.24077584, 0.47698347, 0.68167685, 0.62291954],
       [0.2479919 , 0.59068372, 0.02305439, 0.56794867, 0.6154152 ],
       [0.02258923, 0.11562843, 0.39102703, 0.0760874 , 0.22365392],
       [0.82891619, 0.80859901, 0.06595973, 0.0042932 , 0.05937431],
       [0.40195945, 0.04413777, 0.41708024, 0.99181739, 0.33785653]])

In [38]:
np.random.randn(2)

array([-0.53312773, -1.07395579])

In [39]:
np.random.randn(4,4)

array([[ 0.10226171, -0.49536311,  0.95809143,  0.06171904],
       [ 0.05786514,  0.7361788 ,  0.34802765,  0.18276451],
       [-1.91876948,  0.09904664,  1.31977232, -0.08027837],
       [-0.14589407,  0.71341771,  0.3988759 , -1.03319345]])

In [43]:
np.random.randint(1,100)

99

# Basic Operations

In [13]:
array_a = np.array( [20,30,40,50] )
array_b = np.arange( 4 )

In [14]:
array_a

array([20, 30, 40, 50])

In [15]:
array_b

array([0, 1, 2, 3])

In [17]:
array_c = array_a - array_b

In [18]:
array_c

array([20, 29, 38, 47])

In [20]:
array_d =array_a * array_b 

In [21]:
array_d

array([  0,  30,  80, 150])

In [23]:
array_e = array_c + array_d

In [24]:
array_e

array([ 20,  59, 118, 197])

In [25]:
array_b**2

array([0, 1, 4, 9])

In [28]:
20*np.sin(array_c)

array([ 18.25890501, -13.27267768,   5.92737157,   2.47146245])

In [30]:
array_e < 20

array([False, False, False, False])

In [31]:
arr_a = np.array([[1,1],[0,1]])

In [32]:
arr_b = np.array([[2,0],[3,4]])

In [33]:
arr_a

array([[1, 1],
       [0, 1]])

In [34]:
arr_b

array([[2, 0],
       [3, 4]])

In [35]:
arr_b.ndim

2

In [36]:
arr_a*arr_b

array([[2, 0],
       [0, 4]])

In [37]:
arr_a@arr_b

array([[5, 4],
       [3, 4]])

In [38]:
arr_a.dot(arr_b)

array([[5, 4],
       [3, 4]])

In [39]:
np.add(arr_a, arr_b)

array([[3, 1],
       [3, 5]])

In [40]:
np.sqrt(arr_a)

array([[1., 1.],
       [0., 1.]])

In [41]:
np.exp(arr_b)

array([[ 7.3890561 ,  1.        ],
       [20.08553692, 54.59815003]])

# Indexing, Slicing and Iterating

In [42]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [45]:
a[9]

729

In [46]:
a[1:5]

array([ 1,  8, 27, 64])

In [47]:
a[:6:2]

array([ 0,  8, 64])

In [48]:
a[::-1]

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0])